name: "LABELER ğŸ·ï¸"

on:
  pull_request:

jobs:
  LABELER:
    name: "LABELER ğŸ·ï¸"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "LABELER ğŸ·ï¸"
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"